#Secret is used for store confidential data which means we can share data openly
  # docker-registry   Create a secret for use with a Docker registry
  # generic           Create a secret from a local file, directory, or literal value
  # tls               Create a TLS secret
#imperativeway--> secret
# kubectl create secret generic db-secret \
#   --from-literal=DB_USER=saivardhan \
#   --from-literal=DB_PASS=Nagasai@123
#in k8s we use encode and decode of secrets by using base64
#echo -n 'saivardhan' | base64 --> (encoded) (sol:c2FpdmFyZGhhbg==)
#echo -n 'c2FpdmFyZGhhbg==' | base64 --decode --> (decoded) (sol:saivardhan)
#Declarativeway--> secret
#kubectl get secret name -o yaml
apiVersion: v1 
kind: Secret 
metadata:
  name: secret
type: opaque
data:
  DB_USER: c2FpdmFyZGhhbg==
  DB_PASS: TmFnYXNhaUAxMjM=




